### ISSUE TITLE
hello，why the servo did not have motion？

### ISSUE THREAD

**Issue by KinInEngland** [xeonqq/SpeedyBirdie#13]
hello，here is the description. i connected the battery and then the servo(both the upper one and the lower one) initialized motion but when i press the "start feeding",the motor start rotate and the servo take no action. First time ,i connected the D2 pin and 3V3 pin together because i think that i didn't give a beginning signal.This way is failed.Second , i entered the dev/html page , i try to change the value of servo and then the lower one take some action ,but the upper one still motionless.Do you know why?thx~

**Comment by KinInEngland** [comment]
btw,what is the function of the start buttom?Am i connected correctly?

**Comment by xeonqq** [comment]
The instant change slide bar can control only one servo, you can just swap the pin of the servos, then you can test the other servo with the same slide bar. (I am just too lazy to implement it in software, since it can be easily done like I said before, or just set a different initial value in dev.html, it can also reflect the change.)

As I said [here](https://github.com/xeonqq/SpeedyBirdie/issues/11#issuecomment-1682823264), so closing this.

Seems you are eager to build Speedybirdie, I created a special [consulting service](https://payhip.com/b/PjRZd) in case you really need it.
